language: python
python:
  - "2.6"
  - "2.7"
  - "pypy"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5.0b3"
  - "3.5-dev"
  - "nightly"

env:
  - JYTHON=true
  - JYTHON=false

before_install:
  - export JYTHON_URL='http://downloads.sourceforge.net/project/jython/jython/2.5.2/jython_installer-2.5.2.jar'
  - if [ "$JYTHON" == "true" ]; then wget $JYTHON_URL -O jython_installer.jar; java -jar jython_installer.jar -s -d $HOME/jython; export PATH=$HOME/jython:$PATH; fi

before_script: 
- if [ "$JYTHON" == "true" ]; then export PYTHON_EXE=jython; jython -c "print ''"; else export PYTHON_EXE=python; fi
- ls
- pwd

install:
- pip install -e .
- pip install -r requirements.txt

script:
- nosetests
- cd pytorrent && nosetests && cd ..
- python pytorrent/tests/unitest.py

matrix:
  fast_finish:true 
  allow_failures:
    - python: 3.2
    - python: 3.3
    - python: 3.4
    - python: 3.5.0b3
    - python: 3.5-dev
    - python: nightly
    - env: JYTHON=true
